// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnAZlLwN7fVErjTJyjFCDX_oDrkZNcy8Y',
    appId: '1:738767565652:web:3b7831be30308e4bf94ec1',
    messagingSenderId: '738767565652',
    projectId: 'message-boa',
    authDomain: 'message-boa.firebaseapp.com',
    storageBucket: 'message-boa.firebasestorage.app',
    measurementId: 'G-NNEEVJEYB0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3fPGZFd3To3eVoeIBaVs_A_Nf2xGyYDg',
    appId: '1:738767565652:android:0c417988b22b0864f94ec1',
    messagingSenderId: '738767565652',
    projectId: 'message-boa',
    storageBucket: 'message-boa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuOcPivf6MyylIlXwlzVERXkva1U-XXmo',
    appId: '1:738767565652:ios:dea9ea47bd92f434f94ec1',
    messagingSenderId: '738767565652',
    projectId: 'message-boa',
    storageBucket: 'message-boa.firebasestorage.app',
    iosBundleId: 'com.example.messageBoardApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuOcPivf6MyylIlXwlzVERXkva1U-XXmo',
    appId: '1:738767565652:ios:dea9ea47bd92f434f94ec1',
    messagingSenderId: '738767565652',
    projectId: 'message-boa',
    storageBucket: 'message-boa.firebasestorage.app',
    iosBundleId: 'com.example.messageBoardApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnAZlLwN7fVErjTJyjFCDX_oDrkZNcy8Y',
    appId: '1:738767565652:web:0205fe78c638422af94ec1',
    messagingSenderId: '738767565652',
    projectId: 'message-boa',
    authDomain: 'message-boa.firebaseapp.com',
    storageBucket: 'message-boa.firebasestorage.app',
    measurementId: 'G-T98DF5WV1P',
  );
}
